# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18c8faba84797d04199047842b6838ed4bf97fd2d2a526cb90edecad192ee08a7424bed18441eb4c8abf9008e487dab699e3972306e522cf90366f79088f28f8

test:
  secret_key_base: 652234c8e6bd9e7d7cc405673642a09302ad14a89a681a5f3d1ce9e2064e55f0f9c7aac8af01f9f951f1417f2a0df8d670d93dd4696af55a838c7d8b68ac93c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
